name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

# 赋予 GITHUB_TOKEN 写入权限，以便部署到 gh-pages 分支
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Enable web support
        run: flutter config --enable-web

      - name: Build Web App
        # 这里的 base-href 必须设置为你的仓库名
        run: flutter build web --base-href "/math-sheet-generator/" --release

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
